runtime: php55
api_version: 1

#handlers:
# - url: /.*
# script: helloworld.php
runtime_config:
 document_root: web
 
 # [START env]
 env_variables:
 # Replace project, instance, database, user and password with the values obtained
 # when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:host=173.194.83.205;port=3306;dbname=mydb
  MYSQL_USER: root
  MYSQL_PASSWORD: '123'
# [END env]
